### ISSUE TITLE
Implement "tags" handling

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-rollout#2]
In short: I have added ["tags" field](https://github.com/trezor/webwallet-data/commit/edc19368e407d68d50cc3ab3fe15735be01d3ba4) to `releases.json`.

The caller could provide the list of tags when calling `getLatestSafeFw`.

* If the provided "tags" list is empty, use the current behaviour with no change
* If the provided "tags" lists is not empty, find if there is a newer firmware that match one of these tags. If there is a match (at least of one of the tags) return the *newest* firmware which can be applied (i.e. not necessarily the matching one).

Let's talk in person about the details.

**Comment by vladimirvolek** [comment]
moved to monorepo

**Comment by prusnak** [comment]
Please use the Transfer issue next time. It has the nice property of creating a redirect. But this is only available for org admins, so ... :-/

Another option is to append to the copy-pasted comment who was the author of the original comment. Now it says "Let's talk in person about the details." written by you, but actually it is me who the person should be talking to.
